version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/mobile'
    schedule:
      interval: 'daily'