name: Feature Request (Backend)
description: Suggest an idea for the backend
title: "feature-request: backend: "
labels: ["enhancement", "backend"]
assignees:
  - ericswpark
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a feature request for the backend!
  - type: textarea
    id: feature-request-description
    attributes:
      label: Description
      description: What do you want to see implemented in the backend?
      placeholder: I wish backend supported feature X...
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context you wish to provide?
      placeholder: Mockups, screenshots, details...
    validations:
      required: false