services:
  backend:
    image: ghcr.io/purdue-cs307-tsundoku/tsundoku-backend:latest
    expose:
      - 3000
    networks:
      - overrides
    environment:
      - TSUNDOKU_BACKEND_GOOGLE_BOOKS_API_KEY
      - TSUNDOKU_BACKEND_APPWRITE_ENDPOINT
      - TSUNDOKU_BACKEND_APPWRITE_PROJECT_ID
      - TSUNDOKU_BACKEND_APPWRITE_API_KEY
      - TSUNDOKU_BACKEND_APPWRITE_MAIN_DB_ID
      - TSUNDOKU_BACKEND_APPWRITE_BOOK_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_AUTHOR_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_EDITION_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_BOOKSTATUS_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_REVIEW_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_CUSTOM_PROP_TEMPLATE_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_CUSTOM_PROP_CATEGORY_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_CUSTOM_PROP_DATA_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_FRIEND_COL_ID
      - TSUNDOKU_BACKEND_APPWRITE_USERDATA_COL_ID
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx-proxy-manager-data:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    networks:
      - overrides
  # Override Traefik ports
  traefik:
    ports: !reset
    networks:
      - overrides

networks:
  overrides:
    name: overrides


volumes:
  nginx-proxy-manager-data:
  nginx-proxy-manager-letsencrypt: