services:
  backend:
    image: ghcr.io/purdue-cs307-tsundoku/tsundoku-backend:latest
    expose:
      - 3000
    networks:
      - overrides
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx-proxy-manager-data:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    networks:
      - overrides
  # Override Traefik ports
  traefik:
    ports: !reset
    networks:
      - overrides

networks:
  overrides:
    name: overrides


volumes:
  nginx-proxy-manager-data:
  nginx-proxy-manager-letsencrypt: