services:
  backend:
    image: ghcr.io/purdue-cs307-tsundoku/tsundoku-backend:latest
    expose:
      - 3000
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host("${_TSUNDOKU_BACKEND_HOSTNAME}")
