name: Mobile iOS Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: iOS Test
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ./mobile
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Detox Build
        run: npx detox build --configuration ios.sim.debug
      - name: Run Detox Test
        run: npx detox test --configuration ios.sim.debug